#!/bin/bash

#!/bin/bash 

#Syntax : echo -e  "\e[ColorCodem Your Tex \e[0m"

# Syntax is 
# echo -e "\e[32m TextOfYourChoice  \e[0m"
echo -e "\e[32m Hi this is my second code \e[0m"

echo -e "\e[33m I am learning bash \e[0m"

echo -e "\e[34m my name is Raj \e[0m"