#!bin/bash

set -e  #ensures to stop if any of the instruction fails

ID=$(id -u)
if [ $ID -ne 0 ]; then 
    echo -e "\e[31m Try executing the script with sudo or a root user \e[0m"
    exit 1
fi

echo -n "installing nginx"
yum install nginx -y  >> /tmp/frontend.log

echo -n "enbale nginx"
systemctl enable nginx
echo -n "start nginx"
systemctl start nginx

echo -n "downloading te code"
curl -s -L -o /tmp/frontend.zip "https://github.com/stans-robot-project/frontend/archive/main.zip"

cd /usr/share/nginx/html
rm -rf *

unzip /tmp/frontend.zip
mv frontend-main/* .
mv static/* .
rm -rf frontend-main README.md
mv localhost.conf /etc/nginx/default.d/roboshop.conf
systemctl restart nginx
 